DEFINE NEW GLOBAL SHARED VARIABLE S-CODALM  AS CHARACTER FORMAT "X(3)".
DEFINE NEW GLOBAL SHARED VARIABLE S-DESALM  AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDIV  AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE lh_Handle AS HANDLE.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODCIA  AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-NOMCIA  AS CHAR INIT "CONTINENTAL S.A.C.".
DEFINE NEW GLOBAL SHARED VARIABLE S-USER-ID AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROSER  AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROFAC  AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-MOVVAL  AS LOGICAL.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODFAM  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDOC  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-FLGSIT  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPODOC  AS CHAR INIT "N".
DEFINE NEW GLOBAL SHARED VARIABLE S-PORCFR  AS DEC INIT 10.
DEFINE NEW GLOBAL SHARED VARIABLE S-TABLA   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-IMPCFR  AS DECIMAL.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROFAC  AS INTEGER.

DEFINE NEW GLOBAL SHARED VARIABLE S-PROVEE  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPOCMB  AS DECIMAL.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODMON  AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-AFTIGV  AS LOG.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODPRO  AS CHAR.

DEFINE NEW GLOBAL SHARED TEMP-TABLE DREQ     LIKE LG-DREQU.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DCST     LIKE ImDCstP.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DCST2    LIKE ImDCst.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DTAB     LIKE LG-TABLA.
DEFINE NEW GLOBAL SHARED TEMP-TABLE CCMP     LIKE ImCOCmp.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DCMP     LIKE ImDOCmp.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DCOT     LIKE ImDOCmp.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DARANCEL LIKE ImArancel.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DETA     LIKE ImDFacCom.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DDUA     LIKE ImDDua.

DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM  LIKE integral.almdmov.
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM2 LIKE integral.lg-liqcsgd.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DREP LIKE integral.Almdrequ.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-DOSER LIKE LG-DOSER.
DEFINE NEW GLOBAL SHARED TEMP-TABLE RUTA LIKE Di-RutaC.

dEFINE NEW GLOBAL SHARED VARIABLE input-var-1 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-3 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-1 AS ROWID.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-3 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE s-tipo       AS CHARACTER.

s-codalm = "11".
s-coddiv = "00000".
s-user-id = "ADMIN".





