DEFINE NEW GLOBAL SHARED VARIABLE S-CODALM  AS CHARACTER FORMAT "X(3)".
DEFINE NEW GLOBAL SHARED VARIABLE S-DESALM  AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDIV  AS CHARACTER INIT '00000'.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODCIA  AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-NOMCIA  AS CHAR INIT "TAI HENG S.A.".
DEFINE NEW GLOBAL SHARED VARIABLE S-USER-ID AS CHAR.

DEFINE NEW GLOBAL SHARED VARIABLE input-var-1 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-3 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-1 AS ROWID.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-3 AS CHARACTER.
