DEFINE NEW GLOBAL SHARED VARIABLE s-acceso-total AS LOG NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE s-flgest AS CHAR.
/* Para Librerias en memoria */
/* 1. Para levanta la rutina web/web-library.p */
DEF NEW GLOBAL SHARED VAR sh_hProcPricing AS HANDLE NO-UNDO.
DEF NEW GLOBAL SHARED VAR sh_hProcSapLibrary AS HANDLE NO-UNDO.
/* ******************************************* */
DEFINE NEW GLOBAL SHARED VARIABLE S-CODIGV   AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-TpoFac   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE f-CodDoc  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-PTOVTA   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-SERCJA   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-SERALM   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-TIPO     AS CHAR.
DEF NEW GLOBAL SHARED VAR lh_handle_01 AS HANDLE.
DEF NEW GLOBAL SHARED VAR S-CODCIA   AS INTEGER INIT 1.
DEF NEW GLOBAL SHARED VAR CL-CODCIA   AS INTEGER INIT 0.
DEF NEW GLOBAL SHARED VAR PV-CODCIA  AS INTEGER INIT 0.
DEF NEW GLOBAL SHARED VAR S-NOMCIA   AS CHAR INIT "CONTINENTAL S.A.C".
DEF NEW GLOBAL SHARED VAR S-USER-ID  AS CHAR INIT 'ADMIN'.

DEF NEW GLOBAL SHARED TEMP-TABLE ITEM LIKE FacDPedi.

DEF NEW GLOBAL SHARED TEMP-TABLE ITEM-2 LIKE FacDPedi.
DEF NEW GLOBAL SHARED TEMP-TABLE ITEM-3 LIKE FacDPedi.

DEF NEW GLOBAL SHARED VAR S-CODDIV   AS CHAR INIT "00001".
DEF NEW GLOBAL SHARED VAR S-NROSER   AS INTEGER.
DEF NEW GLOBAL SHARED VAR S-TPOPED AS CHAR.
DEF NEW GLOBAL SHARED VAR S-NROCOT   AS CHARACTER.
DEF NEW GLOBAL SHARED VAR S-CODALM   AS CHARACTER.
DEF NEW GLOBAL SHARED VAR s-FmaPgo AS CHAR.
DEF NEW GLOBAL SHARED VAR pCodDiv AS CHAR.
DEF NEW GLOBAL SHARED VAR S-CODDOC   AS CHAR.

DEF NEW GLOBAL SHARED VAR S-CODCLI   AS CHAR.
DEF NEW GLOBAL SHARED VAR S-CNDVTA   AS CHAR.
DEF NEW GLOBAL SHARED VAR S-TPOCMB AS DECIMAL.  
DEF NEW GLOBAL SHARED VAR S-CODMON AS INTEGER.
DEF NEW GLOBAL SHARED VAR S-FLGIGV AS LOGICAL.
DEF NEW GLOBAL SHARED VAR S-PORIGV AS DECIMAL.

DEF NEW GLOBAL SHARED VAR lh_Handle  AS HANDLE.

DEF NEW GLOBAL SHARED VAR s-nrodec AS INT.

DEF NEW GLOBAL SHARED VAR s-Sunat-Activo AS LOGICAL.
DEF NEW GLOBAL SHARED VAR s-FlgSit AS CHAR.

DEF NEW GLOBAL SHARED VAR s-nroped AS CHAR.

DEF NEW GLOBAL SHARED VAR s-adm-new-record AS CHAR.

DEF NEW GLOBAL SHARED VAR s-FlgEmpaque LIKE GN-DIVI.FlgEmpaque.

DEF NEW GLOBAL SHARED VAR S-CMPBNTE  AS CHAR.

DEF NEW GLOBAL SHARED TEMP-TABLE T-DPEDI LIKE FacDPedi.
DEF NEW GLOBAL SHARED VAR s-CodTer AS CHAR.
DEF NEW GLOBAL SHARED VAR S-TPOMARCO AS CHAR.

DEF NEW GLOBAL SHARED VAR s-CodVen AS CHAR.

DEF NEW GLOBAL SHARED VAR s-DiasVtoPed AS INTE.
DEF NEW GLOBAL SHARED VAR s-FlgEmpaque LIKE GN-DIVI.FlgEmpaque.
DEF NEW GLOBAL SHARED VAR s-DiasVtoCot AS INT.

DEF NEW GLOBAL SHARED VAR s-MinimoPesoDia AS DEC.
DEF NEW GLOBAL SHARED VAR s-MaximaVarPeso AS DEC.
DEF NEW GLOBAL SHARED VAR s-MinimoDiasDespacho AS DEC.

DEF NEW GLOBAL SHARED VAR s-ClientesVIP AS LOG.
DEF NEW GLOBAL SHARED VAR s-nivel-acceso AS INT INIT 0 NO-UNDO.

DEF NEW GLOBAL SHARED VAR s-Solicita-Aprobacion AS LOGICAL.
DEF NEW GLOBAL SHARED VAR s-import-ibc AS LOG INIT NO.
DEF NEW GLOBAL SHARED VAR s-import-b2b AS LOG INIT NO.
DEF NEW GLOBAL SHARED VAR s-import-cissac AS LOG INIT NO.
DEFINE NEW GLOBAL SHARED TEMP-TABLE tt-listaexpress-sugeridos LIKE w-report.
DEFINE NEW GLOBAL SHARED VAR x-order-type AS CHAR.     /* PREMIUM/STANDARD */

DEF NEW GLOBAL SHARED VAR s-VerificaStock AS LOG INIT YES.
DEF NEW GLOBAL SHARED VAR s-codlinea AS CHAR.
DEF NEW GLOBAL SHARED VAR s-FlgTipoVenta LIKE GN-DIVI.FlgPreVta.
DEF NEW GLOBAL SHARED VAR s-codmat AS CHAR.
DEF NEW GLOBAL SHARED TEMP-TABLE PEDI  LIKE FacDPedi.
DEF NEW GLOBAL SHARED VAR s-codref AS CHAR.
DEF NEW GLOBAL SHARED VAR s-nroref AS CHAR.
DEF NEW GLOBAL SHARED VAR s-VentaMayorista LIKE GN-DIVI.VentaMayorista.
DEF NEW GLOBAL SHARED VAR s-DiasVtoPed AS INTE.
DEF NEW GLOBAL SHARED VAR s-FlgEmpaque LIKE GN-DIVI.FlgEmpaque.
DEFINE NEW GLOBAL SHARED VARIABLE s-TpoPed2 AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-Tipo-Abastecimiento AS CHAR INIT "NORMAL".
DEFINE NEW GLOBAL SHARED VAR s-FlgMinVenta LIKE GN-DIVI.FlgMinVenta.

DEFINE NEW GLOBAL SHARED TEMP-TABLE DETA LIKE CcbDDocu.
DEFINE NEW GLOBAL SHARED VARIABLE S-PORDTO AS DECIMAL.  
