DEFINE NEW GLOBAL SHARED VARIABLE S-CODCIA   AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE CL-CODCIA   AS INTEGER INIT 0.
DEFINE NEW GLOBAL SHARED VARIABLE PV-CODCIA  AS INTEGER INIT 0.
DEFINE NEW GLOBAL SHARED VARIABLE S-NOMCIA   AS CHAR INIT "CONTINENTAL S.A.C".
DEFINE NEW GLOBAL SHARED VARIABLE S-USER-ID  AS CHAR INIT 'ADMIN'.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDOC   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDIV   AS CHAR INIT "00000".
DEFINE NEW GLOBAL SHARED VARIABLE S-NROSER   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODALM   AS CHAR.
DEF NEW GLOBAL SHARED VAR pCodDiv AS CHAR.
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM   LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED VARIABLE lh_Handle  AS HANDLE.

