DEFINE TEMP-TABLE ttImport1
FIELD testField1 AS CHARACTER
FIELD testField2 AS DECIMAL
FIELD testField3 AS INTEGER
    INDEX testIndex1 IS PRIMARY testField2 ASCENDING.
DEFINE TEMP-TABLE ttImport2
FIELD testField1 AS CHARACTER
FIELD testField2 AS DECIMAL
FIELD testField3 AS INTEGER
FIELD testField4 AS DATE.
DEFINE TEMP-TABLE ttImport3
FIELD testField1 AS CHARACTER
FIELD testField2 AS DECIMAL
FIELD testField3 AS INTEGER
FIELD testField4 AS DATE
FIELD testfield5 AS LOGICAL.
