DEFINE new global SHARED VARIABLE   s-codcia    AS INTEGER   init 1.
DEFINE new global SHARED VARIABLE   s-nomcia    AS char.
DEFINE new global SHARED VARIABLE   s-periodo   AS INTEGER   INIT 2008.
DEFINE new global SHARED VARIABLE   s-NROMES    AS INTEGER   INIT 1.
DEFINE new global SHARED VARIABLE   s-user-id   AS CHAR      INIT "MASTER".
DEFINE new global SHARED VARIABLE   s-coddiv    AS CHAR      INIT "00000".

DEFINE NEW GLOBAL SHARED VARIABLE S-TABLA    AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODVEN   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CNDVTA   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODIGV   AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE X-NRODEC AS INTEGER INIT 2.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROTAR   AS CHAR.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DRQP LIKE integral.PR-Rqprod.

DEFINE new global SHARED VARIABLE s-codbal    AS INTEGER    init 1.
DEFINE new global SHARED VARIABLE CB-CODCIA   AS INTEGER    init 0.
DEFINE new global SHARED VARIABLE PV-CODCIA   AS INTEGER    init 0.
DEFINE new global SHARED VARIABLE CL-CODCIA   AS INTEGER    init 0 .
DEFINE new global SHARED VARIABLE CB-NIVELES  AS CHAR       init "2,3,5".
DEFINE new global SHARED VARIABLE CB-MAXNIVEL AS INTEGER    init 8.
DEFINE new global SHARED VARIABLE s-codcli    AS CHAR.
DEFINE new global SHARED VARIABLE s-codpro    AS CHAR.
DEFINE new global SHARED VARIABLE s-fchdoc    AS DATE.
DEFINE new global SHARED VARIABLE s-codmon    AS INT INIT 1.
DEFINE new global SHARED VARIABLE s-tpocmb    AS DEC INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-PROVEE  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPODOC AS CHAR INIT "N".
DEFINE NEW GLOBAL SHARED VARIABLE S-PORCFR AS DEC INIT 10.
DEFINE NEW GLOBAL SHARED VARIABLE S-AFTIGV  AS LOG.
DEFINE NEW GLOBAL SHARED VARIABLE s-HojaRuta AS LOG.
DEFINE NEW GLOBAL SHARED VARIABLE x-tipo     AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CONDIC   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-imptot as decimal.
DEFINE NEW GLOBAL SHARED VARIABLE s-nroref as char.
DEFINE NEW GLOBAL SHARED VARIABLE s-MonCta AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE s-CodCta AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE S-PORGAS AS DECIMAL.
DEFINE NEW GLOBAL SHARED VARIABLE S-FLGSIT AS CHAR.

DEFINE NEW GLOBAL SHARED VARIABLE   S-TRASLADO AS CHAR INIT "E".
                                                                     
DEFINE new global SHARED VAR lh_Handle AS HANDLE.
DEFINE new global SHARED VAR S-CODDOC  AS CHAR.

DEFINE NEW GLOBAL SHARED VARIABLE input-var-1  AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-2  AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-3  AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-1 AS ROWID.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-3 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VAR s-local AS CHAR.
DEFINE NEW GLOBAL SHARED VAR s-fecha AS DATE.
DEFINE NEW GLOBAL SHARED VAR s-hasta AS DATE.
DEFINE NEW GLOBAL SHARED VAR s-codope AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE f-CodDoc  AS CHAR.
DEFINE new global SHARED VARIABLE x-flag    AS LOGICAL.  

DEFINE new global SHARED TEMP-TABLE RMOV LIKE cb-dmov.
DEFINE new global SHARED TEMP-TABLE VMOV LIKE cb-cmov.
DEFINE new global SHARED TEMP-TABLE MVTO LIKE CcbDMvto.
DEFINE NEW global SHARED TEMP-TABLE ALMOV LIKE Almcmov.
DEFINE NEW global SHARED TEMP-TABLE T-DDET LIKE Cb-DDET.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DCMP LIKE LG-DOCmp.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-DOSER LIKE LG-DOSER.
DEFINE NEW GLOBAL SHARED TEMP-TABLE RUTA LIKE Di-RutaC.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-CcbCCaja LIKE CcbCCaja.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-CcbDCaja LIKE CcbDCaja.
DEFINE NEW GLOBAL SHARED TEMP-TABLE PEDI LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-DROL LIKE CP-DROL.

DEFINE NEW GLOBAL SHARED VARIABLE fFchAst AS DATE NO-UNDO.
 

DEFINE NEW GLOBAL SHARED VARIABLE s-periodo AS INTEGER FORMAT "9999".
DEFINE NEW GLOBAL SHARED VARIABLE S-CODALM  AS CHARACTER INIT '11' FORMAT "X(3)".
DEFINE NEW GLOBAL SHARED VARIABLE S-DESALM  AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDIV  AS CHARACTER INIT '00000'.
DEFINE NEW GLOBAL SHARED VARIABLE lh_Handle AS HANDLE.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODCIA  AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-NOMCIA  AS CHAR INIT "CONTINENTAL S.A.C".
DEFINE NEW GLOBAL SHARED VARIABLE S-USER-ID AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROSER  AS INTEGER INIT 0.
DEFINE NEW GLOBAL SHARED VARIABLE S-MOVVAL  AS LOGICAL.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODFAM  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPOMOV   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODMOV   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-MOVTRF   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-TIPMOV   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-ROWID   AS ROWID.
DEFINE NEW GLOBAL SHARED VARIABLE S-IMPGAS AS DECIMAL.
DEFINE NEW GLOBAL SHARED VARIABLE S-PTOVTA   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-SERCJA   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-SERALM   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODTER   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-codcja AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-PORDTO AS DEC.
DEFINE NEW GLOBAL SHARED VARIABLE S-PORIGV AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-ROWID  AS ROWID.

DEFINE NEW GLOBAL SHARED TEMP-TABLE T-Rutad LIKE integral.DI-Rutad.                                                                   
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM LIKE integral.almdmov.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DREP LIKE integral.Almdrequ.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DOTRB LIKE integral.Almdotrb.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DETA LIKE CcbDDocu.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DMOV LIKE almdmov.    
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-GLOSA LIKE CcbGDocu.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-RDOC  LIKE CcbRDocu.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-RutaDv NO-UNDO LIKE INTEGRAL.Di-RutaDv.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-MATG LIKE almmmatg.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-CMOV LIKE AlmCMov.

DEFINE NEW GLOBAL SHARED TEMP-TABLE DREQ LIKE integral.LG-DREQU.

DEFINE NEW GLOBAL SHARED VARIABLE S-CODDOC AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODPRO AS CHARACTER.

DEFINE NEW GLOBAL SHARED VARIABLE input-var-1 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-3 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-1 AS ROWID.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-3 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE s-tipo       AS CHARACTER.

DEFINE NEW GLOBAL SHARED TEMP-TABLE t-prev 
      FIELD Tipo AS CHAR
      FIELD Subalm AS CHAR
      FIELD Codmov AS INTEGER
      FIELD NroGui AS CHAR
      FIELD Periodo LIKE cb-dmov.periodo
      FIELD NroMes LIKE cb-dmov.nromes
      FIELD Codope LIKE cb-dmov.codope
      FIELD Codcta LIKE cb-dmov.codcta
      FIELD CodDiv LIKE cb-dmov.coddiv
      FIELD Codmon LIKE cb-dmov.codmon
      FIELD Fchdoc LIKE cb-dmov.fchdoc
      FIELD Coddoc LIKE cb-dmov.coddoc
      FIELD Nrodoc LIKE cb-dmov.nrodoc
      FIELD Glodoc LIKE cb-dmov.glodoc
      FIELD Tpocmb LIKE cb-dmov.tpocmb
      FIELD TpoMov LIKE cb-dmov.tpomov
      FIELD ImpMn1 LIKE cb-dmov.impmn1 
      FIELD ImpMn2 LIKE cb-dmov.impmn2
      FIELD cco    LIKE cb-dmov.cco  
      FIELD clfaux LIKE cb-dmov.Clfaux
      FIELD codaux LIKE cb-dmov.Codaux
      FIELD Codref LIKE cb-dmov.codref
      FIELD Nroref LIKE cb-dmov.nroref
      INDEX IDX01 Tipo.

DEFINE NEW GLOBAL SHARED VARIABLE C-CODALM  AS CHARACTER FORMAT "X(3)".
DEFINE NEW GLOBAL SHARED VARIABLE ORDTRB    AS CHARACTER .
DEFINE NEW GLOBAL SHARED VARIABLE c-CODMOV  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE L-NROSER  AS CHAR.

ASSIGN s-periodo = 2008
       S-CODCIA  = 1.



DEF NEW GLOBAL SHARED TEMP-TABLE T-Ajuste
    FIELD CodMat LIKE Almmmatg.CodMat
    FIELD DesMat LIKE Almmmatg.CodMat
    FIELD UndStk LIKE Almmmatg.CodMat
    FIELD CodAlm LIKE Almdmov.Codalm
    FIELD StkSub LIKE Almdmov.CanDes
    FIELD Dife   LIKE Almdmov.CanDes
    FIELD TipMov LIKE Almdmov.TipMov
    FIELD TipInv LIKE Almdmov.TipMov
    INDEX Idx01 IS UNIQUE PRIMARY
          CodMat DESCENDING
    INDEX Idx02
          TipMov DESCENDING
          TipInv DESCENDING.

