
/*Variables Cabecera*/
DEFINE VARIABLE cCodEmisor AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cCodRecep  AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE iNroCon    AS INTEGER     NO-UNDO FORMAT ">>>>>>>>>>>>>9".
DEFINE VARIABLE iTpoOrd    AS INTEGER     NO-UNDO INIT 220.
DEFINE VARIABLE cNroOrd    AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cTipDoc    AS CHARACTER   NO-UNDO FORMAT "X(6)" INIT "ORDERS".
DEFINE VARIABLE cFchGenDoc AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cFchEntMax AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cFchEntSol AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cCodEmpCom AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cCodPtoVta AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cCodPro    AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cCodEntBie AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cCodEmpFac AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE cLugEntFac AS CHARACTER   NO-UNDO FORMAT "X(35)".
DEFINE VARIABLE dImpGenVta AS DECIMAL     NO-UNDO FORMAT ">>>>>>>>>>>>>>9.999".
DEFINE VARIABLE dCodMndOrd AS CHARACTER   NO-UNDO.
DEFINE VARIABLE iFchRefDsc AS INTEGER     NO-UNDO INIT 21 FORMAT ">>9".
DEFINE VARIABLE iNroDiaDsc AS INTEGER     NO-UNDO FORMAT ">>9".
DEFINE VARIABLE dValTotCom AS DECIMAL     NO-UNDO FORMAT ">>>>>>>>>>>>>>9.999".

/*Variables Detalle*/
DEFINE VARIABLE iNroItem AS INTEGER     NO-UNDO FORMAT ">>>>>9" EXTENT 15.
DEFINE VARIABLE cCodMat  AS CHARACTER   NO-UNDO FORMAT "X(6)"   EXTENT 15.
DEFINE VARIABLE dCanPed  AS DECIMAL     NO-UNDO FORMAT ">>>>>>>>>>>9.999" EXTENT 15.
DEFINE VARIABLE cUndMed  AS CHARACTER   NO-UNDO FORMAT "X(3)" EXTENT 15.
DEFINE VARIABLE dValLin  AS DECIMAL     NO-UNDO FORMAT ">>>>>>>>>>>>>>9.999"  EXTENT 15.
DEFINE VARIABLE dPreBru  AS DECIMAL     NO-UNDO FORMAT ">>>>>>>>>>9.9999"     EXTENT 15.
DEFINE VARIABLE dPreNet  AS DECIMAL     NO-UNDO FORMAT ">>>>>>>>>>9.9999"     EXTENT 15.
DEFINE VARIABLE dValIGV  AS DECIMAL     NO-UNDO FORMAT ">>>>>>>>>>>>>>9.999"  EXTENT 15.
DEFINE VARIABLE iSecDsc1 AS INTEGER     NO-UNDO FORMAT "9" EXTENT 15.
DEFINE VARIABLE iSecDsc2 AS INTEGER     NO-UNDO FORMAT "9" EXTENT 15.
DEFINE VARIABLE iSecDsc3 AS INTEGER     NO-UNDO FORMAT "9" EXTENT 15.
DEFINE VARIABLE iPorDsc1 AS INTEGER     NO-UNDO FORMAT ">>>>>9.9999" EXTENT 15.
DEFINE VARIABLE iPorDsc2 AS INTEGER     NO-UNDO FORMAT ">>>>>9.9999" EXTENT 15.
DEFINE VARIABLE iPorDsc3 AS INTEGER     NO-UNDO FORMAT ">>>>>9.9999" EXTENT 15.

