DEFINE NEW GLOBAL SHARED VARIABLE lh_Handle  AS HANDLE.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODCIA   AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-NOMCIA   AS CHAR INIT "CONTINENTAL S.A.C".
DEFINE NEW GLOBAL SHARED VARIABLE S-USER-ID  AS CHAR INIT "ADMIN".
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDOC   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODREF   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROREF   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDIV   AS CHAR INIT "00001".
DEFINE NEW GLOBAL SHARED VARIABLE S-NROSER   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODVEN   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODALM   AS CHAR INIT '03'.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODMOV   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODMON   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-DESALM   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODCLI   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-TIPVTA   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPOPED   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROTAR   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CNDVTA   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODMAT   AS CHAR INIT '000150'.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODIGV   AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPOPED   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-PTOVTA   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-IMPTOT   AS DEC.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROCOT   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROPED   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-PRECOT   AS LOG.
DEFINE NEW GLOBAL SHARED VARIABLE S-FLGSIT   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-OpSys    AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE s-TipMat   AS CHARACTER INIT 'VTA'.
DEFINE NEW GLOBAL SHARED VARIABLE s-Tabla    AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE s-Rowid    AS ROWID.
DEFINE NEW GLOBAL SHARED VARIABLE S-TpoFac   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-import-ibc AS LOG INIT NO.
DEFINE NEW GLOBAL SHARED VARIABLE s-PorIgv LIKE Ccbcdocu.PorIgv.
DEFINE NEW GLOBAL SHARED VARIABLE s-codbko   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-tarjeta   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODPRO   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE fathWH AS HANDLE NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE s-DNIClie  AS CHAR.

DEFINE new global SHARED VARIABLE   CB-CODCIA   AS INTEGER    init 0.
DEFINE new global SHARED VARIABLE   PV-CODCIA   AS INTEGER    init 0.
DEFINE new global SHARED VARIABLE   CL-CODCIA   AS INTEGER    init 0 .
DEFINE new global SHARED VARIABLE   CB-NIVELES  AS CHAR       init "2,3,5".
DEFINE new global SHARED VARIABLE   CB-MAXNIVEL AS INTEGER    init 8.

DEFINE NEW GLOBAL SHARED VARIABLE S-TPOCMB AS DECIMAL.  
DEFINE NEW GLOBAL SHARED VARIABLE S-PORDTO AS DECIMAL.  
DEFINE NEW GLOBAL SHARED VARIABLE input-var-1 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-3 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-4 AS CHARACTER.

/* VARIABLES PARA COTIZACIONES */
DEF NEW GLOBAL SHARED VAR s-DiasVtoCot LIKE GN-DIVI.DiasVtoCot.
DEF NEW GLOBAL SHARED VAR s-DiasVtoPed LIKE GN-DIVI.DiasVtoPed.
DEF NEW GLOBAL SHARED VAR s-DiasAmpCot LIKE GN-DIVI.DiasAmpCot.
DEF NEW GLOBAL SHARED VAR s-FlgEmpaque LIKE GN-DIVI.FlgEmpaque.
DEF NEW GLOBAL SHARED VAR s-FlgMinVenta LIKE GN-DIVI.FlgMinVenta.
DEF NEW GLOBAL SHARED VAR s-FlgRotacion LIKE GN-DIVI.FlgRotacion.
DEF NEW GLOBAL SHARED VAR s-FlgPicking LIKE GN-DIVI.FlgPicking.
DEF NEW GLOBAL SHARED VAR s-FlgBarras LIKE GN-DIVI.FlgBarras.
DEF NEW GLOBAL SHARED VAR s-VentaMayorista LIKE GN-DIVI.VentaMayorista.
DEF NEW GLOBAL SHARED VAR s-VentaMinorista LIKE GN-DIVI.VentaMinorista.
DEF NEW GLOBAL SHARED VAR s-Almacenes AS CHAR.
DEFINE NEW GLOBAL SHARED VAR s-adm-new-record AS CHAR.

DEFINE NEW GLOBAL SHARED VAR S-SerGui AS INTEGER.
DEFINE NEW GLOBAL SHARED VAR S-SerFac AS INTEGER.
DEFINE NEW GLOBAL SHARED VAR S-SerBol AS INTEGER.
DEFINE NEW GLOBAL SHARED VAR pCodAlm AS CHAR.
DEFINE NEW GLOBAL SHARED VAR p-monto  AS DECIMAL.

DEFINE NEW GLOBAL SHARED TEMP-TABLE CDOCU LIKE VtaCDocu.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DDOCU LIKE VtaDDocu.

DEFINE NEW GLOBAL SHARED TEMP-TABLE T-CPEDI NO-UNDO LIKE FacCPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM NO-UNDO LIKE FacDPedm.
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM-2 NO-UNDO LIKE FacDPedm.
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM-3 NO-UNDO LIKE FacDPedm.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DETA LIKE CcbDDocu.
DEFINE NEW GLOBAL SHARED TEMP-TABLE PEDI LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-DPEDI LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE PEDI-1 LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE PEDI-2 LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE PEDI-3 NO-UNDO LIKE FacDPedi.

DEFINE NEW GLOBAL SHARED VARIABLE X-NRODEC AS INTEGER INIT 2.

