DEFINE NEW GLOBAL SHARED VARIABLE s-flgest AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-Lineas-Validas AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-Tipo-Lista AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE s-Divisiones AS CHAR INIT '00015'.
DEFINE NEW GLOBAL SHARED VARIABLE s-CanalVenta AS CHAR INIT 'TDA'.
DEFINE NEW GLOBAL SHARED VARIABLE s-Tabla AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE s-Codigo AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE s-Tabla-1 AS CHARACTER.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-FacTabla LIKE FacTabla.
DEF NEW GLOBAL SHARED VAR s-Tabla AS CHAR.
DEF NEW GLOBAL SHARED VAR s-FlgMinVenta LIKE GN-DIVI.FlgMinVenta.
DEFINE NEW GLOBAL SHARED VARIABLE s-Sunat-Activo AS LOG.
DEF NEW GLOBAL SHARED VAR s-VentaMayorista LIKE GN-DIVI.VentaMayorista.
DEF NEW GLOBAL SHARED VAR s-VentaMinorista LIKE GN-DIVI.VentaMinorista.
DEFINE NEW GLOBAL SHARED VARIABLE S-CNDVTA   AS CHAR.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-TABLA LIKE VtaTabla.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-DPROM LIKE VtaDctoProm.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-DVOL LIKE PRIDctoVol.
DEFINE NEW GLOBAL SHARED VARIABLE s-task-no  AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE lh_Handle  AS HANDLE.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODCIA   AS INTEGER INIT 001.
DEFINE NEW GLOBAL SHARED VARIABLE S-NOMCIA   AS CHAR INIT "CONTINENTAL S.A.C".
DEFINE NEW GLOBAL SHARED VARIABLE S-USER-ID  AS CHAR INIT "ADMIN".
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDIV   AS CHAR INIT "00015".
DEFINE NEW GLOBAL SHARED VARIABLE pCODDIV    AS CHAR INIT "00015".
DEFINE NEW GLOBAL SHARED VARIABLE s-CodMat   AS CHAR INIT '00012'.
DEFINE NEW GLOBAL SHARED VAR s-acceso-total  AS LOG INIT NO NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDOC   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODCLI   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROSER   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODMON AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODALM   AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE S-PORIGV AS DECIMAL.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPOPED AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-FmaPgo AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPOCMB AS DECIMAL.  
DEFINE NEW GLOBAL SHARED VARIABLE S-CODVEN   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-NRODEC AS INTEGER INIT 2.
DEF NEW GLOBAL SHARED VAR s-FlgIgv AS LOG INIT TRUE.
DEFINE NEW GLOBAL SHARED VARIABLE s-import-ibc AS LOG INIT NO.
DEFINE NEW GLOBAL SHARED VARIABLE s-import-b2b AS LOG INIT NO.
DEFINE NEW GLOBAL SHARED VARIABLE s-import-cissac AS LOG INIT NO.
DEFINE NEW GLOBAL SHARED VAR s-adm-new-record AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CMPBNTE  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROPED   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODTER   AS CHAR.      
DEFINE NEW GLOBAL SHARED VARIABLE S-TPOMARCO AS CHAR.
DEF NEW GLOBAL SHARED VAR s-DiasVtoCot LIKE GN-DIVI.DiasVtoCot.
DEF NEW GLOBAL SHARED VAR s-DiasVtoPed LIKE GN-DIVI.DiasVtoPed.
DEF NEW GLOBAL SHARED VAR s-DiasVtoO_D LIKE GN-DIVI.DiasVtoO_D.
DEF NEW GLOBAL SHARED VAR s-DiasAmpCot LIKE GN-DIVI.DiasAmpCot.
DEF NEW GLOBAL SHARED VAR s-FlgTipoVenta LIKE GN-DIVI.FlgPreVta.
DEF NEW GLOBAL SHARED VAR s-MinimoPesoDia AS DEC.
DEF NEW GLOBAL SHARED VAR s-MaximaVarPeso AS DEC.
DEF NEW GLOBAL SHARED VAR s-MinimoDiasDespacho AS DEC.
DEF NEW GLOBAL SHARED VAR s-ClientesVIP AS LOG.
DEFINE NEW GLOBAL SHARED VAR s-nivel-acceso AS INT INIT 0 NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODIGV  AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-FLGSIT  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODPRO   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-NroVale  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-codbko   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-tarjeta   AS CHAR.
DEF NEW GLOBAL SHARED VAR s-FlgRotacion LIKE GN-DIVI.FlgRotacion.
DEF NEW GLOBAL SHARED VAR s-FlgTipoVenta LIKE GN-DIVI.FlgPreVta.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODREF   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROSER   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROREF   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE X-NRODEC AS INTEGER INIT 2.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROTAR   AS CHAR.
DEF NEW GLOBAL SHARED VAR s-FlgEmpaque LIKE GN-DIVI.FlgEmpaque.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROCOT   AS CHAR.
DEFINE NEW GLOBAL SHARED VAR pCodAlm AS CHAR.

DEFINE NEW GLOBAL SHARED TEMP-TABLE T-MATG LIKE Almmmatg
/*    INDEX Idx00 AS PRIMARY CodMat FchPrmD*/
    .
DEFINE NEW GLOBAL SHARED TEMP-TABLE E-MATG LIKE Almmmatg
    INDEX Idx00 AS PRIMARY CodMat FchPrmD.
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM LIKE Facdpedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM-2 LIKE Facdpedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM-3 LIKE Facdpedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM-LE LIKE Facdpedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-DPEDI LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE PEDI   /*NO-UNDO*/ LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE PEDI-2 LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE PEDI-3 LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-CPEDI NO-UNDO LIKE FacCPedi.
