DEFINE NEW GLOBAL SHARED VARIABLE s-CodOrigen AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-NroOrigen AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-flgest AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-DTOMAX AS DECIMAL.  
DEFINE NEW GLOBAL SHARED VARIABLE S-DTOMAX-Propios AS DECIMAL.  
DEFINE NEW GLOBAL SHARED VARIABLE S-DTOMAX-Terceros AS DECIMAL.  
DEFINE NEW GLOBAL SHARED VARIABLE s-nivel AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-Cantidad-Cero AS LOG.
DEFINE NEW GLOBAL SHARED VARIABLE s-RucCli AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-Atencion AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-NomCli AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-DirCli AS CHAR.

DEFINE NEW GLOBAL SHARED VARIABLE s-Tipo-Abastecimiento AS CHAR INIT "NORMAL".
DEFINE NEW GLOBAL SHARED VARIABLE s-TpoPed2 AS CHAR.
DEF NEW GLOBAL SHARED VAR s-VentaMayorista LIKE GN-DIVI.VentaMayorista.
DEF NEW GLOBAL SHARED VAR s-DiasVtoPed LIKE GN-DIVI.DiasVtoPed.
DEF NEW GLOBAL SHARED VAR s-FlgEmpaque LIKE GN-DIVI.FlgEmpaque.
DEFINE NEW GLOBAL SHARED VARIABLE s-Divisiones AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE s-CanalVenta AS CHAR.
DEFINE NEW GLOBAL SHARED VAR s-acceso-total AS LOG NO-UNDO.
DEFINE NEW GLOBAL SHARED TEMP-TABLE tt-listaexpress-sugeridos LIKE w-report.
DEFINE NEW GLOBAL SHARED VAR x-order-type AS CHAR.     /* PREMIUM/STANDARD */
DEFINE NEW GLOBAL SHARED VARIABLE s-Tabla-1 AS CHARACTER.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-FacTabla LIKE FacTabla.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-DPROM LIKE VtaDctoProm.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-MATG LIKE Almmmatg
/*    INDEX Idx00 AS PRIMARY CodMat FchPrmD*/
    .
DEFINE NEW GLOBAL SHARED TEMP-TABLE TT-MATG LIKE Almmmatg
    INDEX Idx00 AS PRIMARY CodMat FchPrmD
    .
DEF NEW GLOBAL SHARED VAR s-Sunat-Activo AS LOGICAL.
DEF NEW GLOBAL SHARED VAR s-FlgSit AS CHAR.

DEF NEW GLOBAL SHARED VAR s-Solicita-Aprobacion AS LOGICAL.
DEF NEW GLOBAL SHARED VAR s-codmat AS CHAR.
DEF NEW GLOBAL SHARED VAR lh_Handle  AS HANDLE.
DEF NEW GLOBAL SHARED VAR S-CODCIA   AS INTEGER INIT 1.
DEF NEW GLOBAL SHARED VAR CL-CODCIA   AS INTEGER INIT 0.
DEF NEW GLOBAL SHARED VAR PV-CODCIA  AS INTEGER INIT 0.
DEF NEW GLOBAL SHARED VAR S-NOMCIA   AS CHAR INIT "CONTINENTAL S.A.C".
DEF NEW GLOBAL SHARED VAR S-USER-ID  AS CHAR INIT 'ADMIN'.
DEF NEW GLOBAL SHARED VAR S-CODDOC   AS CHAR.
DEF NEW GLOBAL SHARED VAR input-var-1 AS CHARACTER.
DEF NEW GLOBAL SHARED VAR input-var-2 AS CHARACTER.
DEF NEW GLOBAL SHARED VAR input-var-3 AS CHARACTER.
DEF NEW GLOBAL SHARED VAR output-var-1 AS ROWID.
DEF NEW GLOBAL SHARED VAR output-var-2 AS CHARACTER.
DEF NEW GLOBAL SHARED VAR output-var-3 AS CHARACTER.
DEF NEW GLOBAL SHARED VAR output-var-4 LIKE FacDPedi.PreUni.
DEF NEW GLOBAL SHARED VAR output-var-5 LIKE FacDPedi.PorDto.
DEF NEW GLOBAL SHARED TEMP-TABLE ITEM LIKE FacDPedi.
DEF NEW GLOBAL SHARED TEMP-TABLE PEDI  LIKE FacDPedi.
DEF NEW GLOBAL SHARED VAR S-CODDIV   AS CHAR INIT "00001".
DEF NEW GLOBAL SHARED VAR S-NROSER   AS INTEGER.
DEF NEW GLOBAL SHARED VAR S-TPOPED AS CHAR.
DEF NEW GLOBAL SHARED VAR S-NROCOT   AS CHARACTER.
DEF NEW GLOBAL SHARED VAR S-CODALM   AS CHARACTER.
DEF NEW GLOBAL SHARED VAR s-FmaPgo AS CHAR.
DEF NEW GLOBAL SHARED VAR pCodDiv AS CHAR.
DEF NEW GLOBAL SHARED VAR S-CODCLI   AS CHAR.
DEF NEW GLOBAL SHARED VAR S-CNDVTA   AS CHAR.
DEF NEW GLOBAL SHARED VAR S-TPOCMB AS DECIMAL.  
DEF NEW GLOBAL SHARED VAR S-CODMON AS INTEGER.
DEF NEW GLOBAL SHARED VAR S-FLGIGV AS LOGICAL.
DEF NEW GLOBAL SHARED VAR S-PORIGV AS DECIMAL.
DEF NEW GLOBAL SHARED VAR s-adm-new-record AS CHAR.
DEF NEW GLOBAL SHARED VAR s-import-ibc AS LOG.
DEF NEW GLOBAL SHARED VAR s-import-cia AS LOG.
DEF NEW GLOBAL SHARED VAR s-codped AS CHAR.
DEF NEW GLOBAL SHARED VAR s-nroped AS CHAR.
DEF NEW GLOBAL SHARED VAR s-codref AS CHAR.
DEF NEW GLOBAL SHARED VAR s-nroref AS CHAR.
DEF NEW GLOBAL SHARED VAR s-tabla  AS CHAR.
DEF NEW GLOBAL SHARED VAR s-DiasVtoCot AS INT.
DEF NEW GLOBAL SHARED VAR s-CodVen AS CHAR.
DEF NEW GLOBAL SHARED VAR s-nrodec AS INT.
DEF NEW GLOBAL SHARED VAR S-CMPBNTE  AS CHAR.
DEF NEW GLOBAL SHARED TEMP-TABLE ITEM-2 LIKE FacDPedi.
DEF NEW GLOBAL SHARED TEMP-TABLE ITEM-3 LIKE FacDPedi.
DEF NEW GLOBAL SHARED TEMP-TABLE T-DPEDI LIKE FacDPedi.
DEF NEW GLOBAL SHARED VAR s-CodTer AS CHAR.
DEF NEW GLOBAL SHARED VAR S-TPOMARCO AS CHAR.
DEF NEW GLOBAL SHARED VAR s-FlgTipoVenta LIKE GN-DIVI.FlgPreVta.
DEF NEW GLOBAL SHARED VAR s-MinimoPesoDia AS DEC.
DEF NEW GLOBAL SHARED VAR s-MaximaVarPeso AS DEC.
DEF NEW GLOBAL SHARED VAR s-MinimoDiasDespacho AS DEC.
DEF NEW GLOBAL SHARED VAR s-nivel-acceso AS INT INIT 0 NO-UNDO.
DEF NEW GLOBAL SHARED VAR s-ClientesVIP AS LOG.

DEF NEW GLOBAL SHARED VAR s-import-ibc AS LOG INIT NO.
DEF NEW GLOBAL SHARED VAR s-import-b2b AS LOG INIT NO.
DEF NEW GLOBAL SHARED VAR s-import-cissac AS LOG INIT NO.

DEF NEW GLOBAL SHARED VAR s-VerificaStock AS LOG INIT YES.
