DEFINE NEW GLOBAL SHARED VARIABLE lh_Handle  AS HANDLE.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODCIA   AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-NOMCIA   AS CHAR INIT "TAI HENG S.A.".
DEFINE NEW GLOBAL SHARED VARIABLE S-USER-ID  AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDOC   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODDIV   AS CHAR INIT "00000".
DEFINE NEW GLOBAL SHARED VARIABLE S-NROSER   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-PERIODO  AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROMES  AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-NROTAR   AS CHAR.

DEFINE NEW GLOBAL SHARED VARIABLE S-CODVEN   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODALM   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODMOV   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODMON   AS INTEGER.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODCLI   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-TIPVTA   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CNDVTA   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-IMPFLE   AS DECIMAL.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODMAT   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODIGV   AS INTEGER INIT 1.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPOPED   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-LisNiv   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-PTOVTA   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-IMPTOT   AS DEC.

DEFINE NEW GLOBAL SHARED VAR S-SerGui AS INTEGER.
DEFINE NEW GLOBAL SHARED VAR S-SerFac AS INTEGER.
DEFINE NEW GLOBAL SHARED VAR S-SerBol AS INTEGER.

DEFINE NEW GLOBAL SHARED TEMP-TABLE ITEM LIKE FacDPedm.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DETA LIKE CcbDDocu.
DEFINE NEW GLOBAL SHARED TEMP-TABLE PEDI LIKE FacDPedi.
DEFINE NEW GLOBAL SHARED TEMP-TABLE DMOV LIKE almdmov.    
DEFINE NEW GLOBAL SHARED TEMP-TABLE LIQU LIKE FacDLiqu.    
DEFINE NEW GLOBAL SHARED TEMP-TABLE t-prev LIKE cb-dmov.

DEFINE NEW GLOBAL SHARED VARIABLE input-var-1 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE input-var-3 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-1 AS ROWID.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-2 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-3 AS CHARACTER.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-4 LIKE FacDPedi.PreUni.
DEFINE NEW GLOBAL SHARED VARIABLE output-var-5 LIKE FacDPedi.PorDto.

DEFINE NEW GLOBAL SHARED TEMP-TABLE T-CcbDDocu LIKE CcbDDocu.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-CcbCCaja LIKE CcbCCaja.
DEFINE NEW GLOBAL SHARED TEMP-TABLE T-CcbDCaja LIKE CcbDCaja.

DEFINE NEW GLOBAL SHARED VARIABLE S-TIPO     AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-SERCJA   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE S-CODTER   AS CHAR.      
DEFINE NEW GLOBAL SHARED VARIABLE S-PTOVTA   AS INT.
DEFINE NEW GLOBAL SHARED VARIABLE C-CODDOC   AS CHAR INITIAL "FAC".

DEFINE NEW GLOBAL SHARED VARIABLE C-clfCli   AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE S-TPOCMB AS DECIMAL.  

DEFINE NEW GLOBAL SHARED VARIABLE s-nivel AS CHAR.
DEFINE NEW GLOBAL SHARED VARIABLE X-NRODEC AS INTEGER INIT 2.
