/* AccessWebSiteUsingSockets.p */
DEFINE STREAM outfile.
DEFINE VARIABLE vSocket AS HANDLE    NO-UNDO.
DEFINE VARIABLE wstatus AS LOGICAL   NO-UNDO.
DEFINE VARIABLE vStr    AS CHARACTER NO-UNDO.
DEFINE VARIABLE vBuffer AS MEMPTR    NO-UNDO.
DEFINE VARIABLE wloop   AS LOGICAL   NO-UNDO.

DEFINE VARIABLE wurl AS CHARACTER FORMAT "X(255)" VIEW-AS FILL-IN SIZE 65 BY 1 INITIAL "http://www.progress.com/" LABEL "Url" NO-UNDO.
DEFINE VARIABLE weditor AS CHARACTER VIEW-AS EDITOR INNER-CHARS 72 INNER-LINES 32 LARGE SCROLLBAR-VERTICAL NO-UNDO.
DEFINE BUTTON b-get LABEL "GET".

DEFINE VARIABLE vhost AS CHARACTER  NO-UNDO.
DEFINE VARIABLE vport AS CHARACTER  NO-UNDO.
DEFINE VARIABLE vpath AS CHARACTER  NO-UNDO.
DEFINE VARIABLE vfile AS CHARACTER  NO-UNDO.

SESSION:APPL-ALERT-BOXES = YES.
FORM wurl b-get SKIP weditor NO-LABELS WITH FRAME DEFAULT-FRAME THREE-D SIDE-LABELS.

ON 'RETURN':U OF wurl OR 'CHOOSE':U OF b-get DO:
    ASSIGN wurl.
    RUN UrlParser(INPUT wurl, OUTPUT vhost, OUTPUT vport, OUTPUT vpath).
    RUN HTTPGet(vhost, vport, vpath, vfile).
    weditor:READ-FILE(vfile).
    RETURN.
END.

RUN adecomm/_tmpfile.p ("i", ".htm", OUTPUT vfile).

MAIN-BLOCK:
DO ON ERROR   UNDO MAIN-BLOCK, LEAVE MAIN-BLOCK ON END-KEY UNDO MAIN-BLOCK, LEAVE MAIN-BLOCK:
    DISPLAY wurl weditor WITH FRAME DEFAULT-FRAME.
    ENABLE wurl b-get weditor WITH FRAME DEFAULT-FRAME.
    WAIT-FOR GO OF CURRENT-WINDOW.
END.
OS-DELETE VALUE(vfile) NO-ERROR.


{aplic/lib/httpget.i}



