DEFINE VAR FORMULA AS CHAR.
DEFINE VAR VALOR-C AS CHAR.
DEFINE VAR VALOR-N AS DECIMAL.
DEFINE VAR VALOR-CA AS DECIMAL.
DEFINE VAR PROCESA AS LOGICAL.
DEFINE VAR S-SIGNO AS CHAR.
DEFINE VAR I AS INTEGER.
DEFINE VAR V1 AS DECIMAL.
DEFINE VAR V2 AS DECIMAL.
DEFINE VAR V3 AS DECIMAL.

V1 = 10.

FORMULA = "".

VALOR-N = 0.
S-SIGNO = "".
PROCESA = FALSE.
DO i = 1 TO NUM-ENTRIES(FORMULA," " ) :
   VALOR-C = ENTRY(i, FORMULA, " " ).   
   IF VALOR-C BEGINS "V1" THEN VALOR-N = 10.      
   ELSE DO :
       IF LOOKUP(VALOR-C,"+,-,*,/") > 0 THEN S-SIGNO = VALOR-C.   
           ELSE VALOR-N = DECIMAL(VALOR-C). 
   END.  
   IF I = 1 THEN VALOR-CA = VALOR-N.   
   IF PROCESA THEN DO :         
      CASE S-SIGNO :     
           WHEN "+" THEN VALOR-CA = ( VALOR-CA + VALOR-N ).
           WHEN "-" THEN VALOR-CA = ( VALOR-CA - VALOR-N ).
           WHEN "*" THEN VALOR-CA = ( VALOR-CA * VALOR-N ).
           WHEN "/" THEN VALOR-CA = ( VALOR-CA / VALOR-N ).
      END CASE.           
   END.       
   
   IF LOOKUP(VALOR-C,"+,-,*,/") > 0 THEN PROCESA = TRUE.
      ELSE PROCESA = FALSE.         
END.

MESSAGE VALOR-CA.
